-- Criação da tabela CLIENTE
CREATE TABLE CLIENTE (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL
);

-- Inserindo alguns registros de teste
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('João Silva', 'joao.silva@email.com');
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Maria Oliveira', 'maria.oliveira@email.com');
INSERT INTO CLIENTE (NOME, EMAIL) VALUES ('Carlos Souza', 'carlos.souza@email.com');

COMMIT;